# Generated by Django 5.1.10 on 2025-06-12 14:32

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Étudiant', 'verbose_name_plural': 'Étudiants'},
        ),
        migrations.AddField(
            model_name='student',
            name='academic_status',
            field=models.CharField(choices=[('REGULAR', 'Régulier'), ('PROBATION', 'Probation'), ('SUSPENDED', 'Suspendu')], default='REGULAR', max_length=20, verbose_name='Statut académique'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.TextField(default='kiroty', verbose_name='Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='allergies',
            field=models.TextField(blank=True, verbose_name='Allergies'),
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_contact',
            field=models.CharField(default='kiroty', max_length=100, verbose_name="Contact d'urgence"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='emergency_phone',
            field=models.CharField(default='224621820065', max_length=15, verbose_name="Téléphone d'urgence"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='F', max_length=1, verbose_name='Genre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AddField(
            model_name='student',
            name='medical_info',
            field=models.TextField(blank=True, verbose_name='Informations médicales'),
        ),
        migrations.AddField(
            model_name='student',
            name='phone',
            field=models.CharField(default='Fe', max_length=15, verbose_name='Téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='registration_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name="Date d'inscription"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(default=1, max_length=20, unique=True, verbose_name="Numéro d'étudiant"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='birth_date',
            field=models.DateField(verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_class',
            field=models.CharField(max_length=100, verbose_name='Classe'),
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=9, verbose_name='Année académique')),
                ('semester', models.IntegerField(choices=[(1, '1er Semestre'), (2, '2ème Semestre')], verbose_name='Semestre')),
                ('average_grade', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Moyenne générale')),
                ('class_rank', models.IntegerField(verbose_name='Rang')),
                ('attendance_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Taux de présence')),
                ('comments', models.TextField(blank=True, verbose_name='Commentaires')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='student.student')),
            ],
            options={
                'verbose_name': 'Dossier académique',
                'verbose_name_plural': 'Dossiers académiques',
                'ordering': ['-academic_year', '-semester'],
                'unique_together': {('student', 'academic_year', 'semester')},
            },
        ),
    ]
